### ISSUE TITLE
ios 9 support?

### ISSUE THREAD

**Issue by mboeru** [singhofmarco/NoSlowAnimations#3]
Hello,

Is there any chance we will see this on ios 9? Currently, after install the OS goes into safe mode.

Thanks!

**Comment by mboeru** [comment]
BTW here is the compatibility list in case you missed it :) https://goo.gl/XafNgZ

**Comment by joemerlino** [comment]
@mboeru Supported in my forked version.

**Comment by singhofmarco** [comment]
iOS 9 is now fully supported!

**Comment by mboeru** [comment]
Thank You! Works great with the latest update.
